/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author victoria
 */
public class BadConsequenceView extends javax.swing.JPanel {
    BadConsequence bcModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
     //REVIEEEEW
    public void setBadConsequence(BadConsequence bc){
        bcModel = bc;
        this.text.setText(bcModel.getText());
        this.level.setText("Niveles: " + bcModel.getLevels());
        if (bcModel instanceof NumericBadConsequence) {
            // Este caso es el utilizado también para los DeathBadConsequence
            this.nVisibleTreasures.setText("Tesoros visibles: " + 
                        ((NumericBadConsequence) bcModel).getNVisibleTreasures());
            this.nHiddenTreasures.setText("Tesoros ocultos: " + 
                        ((NumericBadConsequence) bcModel).getNHiddenTreasures());
        }
        else if (bcModel instanceof SpecificBadConsequence) {
            
        }
        
        repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JLabel();
        specificHidden = new javax.swing.JPanel();
        specificVisible = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pending Bad Consequence\n"));
        setMaximumSize(new java.awt.Dimension(385, 273));
        setMinimumSize(new java.awt.Dimension(350, 250));
        setPreferredSize(new java.awt.Dimension(350, 273));

        text.setFont(new java.awt.Font("Khmer OS", 0, 12)); // NOI18N
        text.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        level.setFont(new java.awt.Font("Khmer OS", 0, 12)); // NOI18N

        nVisibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder("Visible Treasures\n"));
        nVisibleTreasures.setMaximumSize(new java.awt.Dimension(33, 143));
        nVisibleTreasures.setMinimumSize(new java.awt.Dimension(33, 143));
        nVisibleTreasures.setPreferredSize(new java.awt.Dimension(33, 143));

        nHiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder("Hidden Treasures\n"));
        nHiddenTreasures.setMaximumSize(new java.awt.Dimension(33, 143));
        nHiddenTreasures.setMinimumSize(new java.awt.Dimension(33, 143));

        specificHidden.setBorder(javax.swing.BorderFactory.createTitledBorder("Hidden Treasures\n"));

        specificVisible.setBorder(javax.swing.BorderFactory.createTitledBorder("Visible Treasures\n\n"));

        javax.swing.GroupLayout specificVisibleLayout = new javax.swing.GroupLayout(specificVisible);
        specificVisible.setLayout(specificVisibleLayout);
        specificVisibleLayout.setHorizontalGroup(
            specificVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        specificVisibleLayout.setVerticalGroup(
            specificVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(specificHidden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(specificVisible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(nVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificVisible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(specificHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel level;
    private javax.swing.JLabel nHiddenTreasures;
    private javax.swing.JLabel nVisibleTreasures;
    private javax.swing.JPanel specificHidden;
    private javax.swing.JPanel specificVisible;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
