package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author Sofía Almeida Bruno
 * @author María Victoria Granados Pozo
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    BadConsequence pendingBcModel;
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
        badConsequenceView.setVisible(false);
    }

    public void setPendingBadConsequence(BadConsequence aPendingBc) {
        pendingBcModel = aPendingBc;
        badConsequenceView.setBadConsequence(pendingBcModel);
        badConsequenceView.setVisible(true);

        repaint();
        revalidate();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        badConsequenceView = new GUI.BadConsequenceView();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pending", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setMaximumSize(new java.awt.Dimension(356, 236));
        setMinimumSize(new java.awt.Dimension(356, 236));
        setPreferredSize(new java.awt.Dimension(356, 236));

        badConsequenceView.setPreferredSize(new java.awt.Dimension(326, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView;
    // End of variables declaration//GEN-END:variables
}
