package GUI;
import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 *
 * @author Sofía Almeida Bruno
 * @author María Victoria Granados Pozo
 */
public class TreasureView extends javax.swing.JPanel {
    Treasure treasureModel;
    private boolean selected = false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    /**
     * 
     * Consultor de selected
     * @return Devuelve si el tesoro está seleccionado
     */
    public boolean isSelected() {
        return selected;
    }
    
    /**
     * 
     * Consultor de treasureModel
     * @return Devuelve el tesoro representado en la vista
     */
    public Treasure getTreasure() {
        return treasureModel;
    }
    
    public void setTreasure(Treasure aTreasure) {
        treasureModel = aTreasure;
        this.name.setText("<html>" + treasureModel.getName() + "</html>");
        this.bonus.setText("<html>" + treasureModel.getBonus());
        this.type.setText("<html>" + treasureModel.getType());
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        type = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 20, 40)));
        setForeground(new java.awt.Color(177, 20, 40));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Khmer OS", 0, 15)); // NOI18N
        setMaximumSize(new java.awt.Dimension(142, 91));
        setMinimumSize(new java.awt.Dimension(142, 91));
        setPreferredSize(new java.awt.Dimension(142, 91));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        name.setFont(new java.awt.Font("Khmer OS", 0, 12)); // NOI18N
        name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(name);
        name.setBounds(10, 10, 120, 40);

        bonus.setFont(new java.awt.Font("Khmer OS", 0, 12)); // NOI18N
        bonus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(bonus);
        bonus.setBounds(100, 60, 30, 30);

        type.setFont(new java.awt.Font("Khmer OS", 0, 12)); // NOI18N
        type.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        type.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(type);
        type.setBounds(10, 60, 80, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setBackground(Color.lightGray);
        if (selected == true) {
            selected =false;
            this.setOpaque(false);
        }
        else{
            selected = true;
            this.setOpaque(true);
        }        
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
